Http1.1 upgrade
HPI-SWA-Teaching/SWT17-Project-16 pull request #10
Opened 2018-06-18 09:45 UTC by Charle42

2018-06-19 13:44 UTC, hesiod requested changes
Only some minor (mostly formatting/code style) remarks

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2Session.class/instance/newH2WebResponseFor..st
> +				url: 'test.de.url';
If `test.de.url` is supposed to be an invalid or testing DNS name, use `.invalid` or `.test` as per [RFC 2606](https://tools.ietf.org/html/rfc2606).

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2Session.class/instance/receive.st
> +	^ self connection receiveOnFirstStream .
Please remove the dot (code consistency)

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2TestingTool.class/class/testH2WebClientGetRequestOnLocalhost.st
> +testH2WebClientGetRequestOnLocalhost
Consider renaming this method since it does not only try to connect to localhost

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebClient.class/instance/getPathFrom..st
> +		ifTrue:[path := anUrlString]
Maybe add a space after `ifTrue:`?

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +	|  response repeatRedirect repeatAuth |
Nitpick: There are two spaces between `|` and `response`

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +	"XXXX: Fixme. Pre-authenticate the request if we have valid auth credentials"
Is this our FIXME? Where does it come from?

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebClient.class/instance/serverProtocolDictionary.st
> +		serverProtocolDictionary := Dictionary new.	].
Nitpick: There is a spurious tab after `new.` and before `].`

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebClient.class/instance/sslConnect.to..st
> +		ifTrue: [stream sslConnectTo: lastServer withAlpnProtos: (Set  with: 'h2' with: 'http/1.1').
We might want to move `Set  with: 'h2' with: 'http/1.1'` to another method since it is a "magic" value

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebResponse.class/instance/extractDataH2Response..st
> +as yet unclassified
Please move this method to an applicable category

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebResponse.class/instance/extractDataH2Response..st
> +	self headers:  aH2Response header asOrderedCollection  .
Nitpick: Spurious spaces

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebResponse.class/instance/initialize.st
> +	protocol := 'HTTP2'.
What exactly does `protocol` specify here? Where is it used?

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/H2WebResponse.class/instance/initialize.st
> +	protocol := 'HTTP2'.
(Is `'HTTP2'` a magic value?)

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/SecureSocketStream.extension/instance/sslConnectTo.withAlpnProtos..st
> +	XXXX: If you ever see this problem, please inform me."
Is this our FIXME?

2018-06-19 13:44 UTC, hesiod commented on HTTP2-Core.package/SecureSocketStream.extension/instance/sslConnectTo.withAlpnProtos..st
> +	XXXX: If you ever see this problem, please inform me."
(Does it remain applicable?)

2018-06-20 08:27 UTC, Charle42 commented on HTTP2-Core.package/SecureSocketStream.extension/instance/sslConnectTo.withAlpnProtos..st
> +	XXXX: If you ever see this problem, please inform me."
This isn't our FIXME.

Perhaps we should refactor this method ( and probably also sendRequest).

2018-07-06 12:28 UTC, ShirleyNekoDev requested changes
i'll fix my problems

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/convertToH2Request.with..st
> +	aWebRequest headersDo: [:key :value| request  header add: (key asLowercase) ->  value asString. ].
multiple double whitespaces

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/isHttp2..st
> + ^ ((self serverProtocolDictionary at: aServerName) = #h2   or: [ (self serverProtocolDictionary at: aServerName) = #h2c ])
multiple whitespaces before or - linebreak would be better

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendPriorKnowlege.contentBlock..st
> +	(self isHttp2: self serverName  )
broken formatting

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +		[
formatting standards

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +sendRequest: aRequest contentBlock: aContentBlock
big method - refactor it

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendUpgrade.contentBlock..st
> +	aRequest addHeader: 'HTTP2-Settings' value: 'AAMAAABkAARAAAAAAAIAAAAA'.
magic value

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sslConnect.to..st
> +				stream ssl isAlpnSupported ifTrue: [self protocol:  stream ssl alpnSelected asSymbol   for: self serverName]
formatting

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/class/standardHttpContent.st
> +	^#[16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r08 16r00 16r45 16r00
write comment, because I can't read this hex code

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/instance/lockStreamOf.on..st
> +	^aH2WebClient instVarNamed: 'lastServer' put: aServerName;
linebreak after aH2WebClient

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/instance/nextPutAll..st
> +	[
formatting standards

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/instance/peek..st
> +	^	self inStream peek: anInteger.
whitespace problem

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/emptyContentBlock.st
> +	^[:aStream|]
is there an empty block give in the class?

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/exampleContentBlock.st
> +	^[:aStream| aStream nextPutAll: self  exampleContent  ]
whitespace

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/exampleServer.st
> +	^  self exampleScheme , self exampleServerName
whitespace before comma

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testIsHttp.st
> +	webclient protocol: #h2c   for: self class exampleServer.
whitespaces

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testIsHttp2.st
> +	webclient protocol: #h2c   for: self class exampleServer.
whitespaces

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testPrioKnowlegeH2C.st
> +
so many linebreaks

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testPrioKnowlegeHttp.st
> +	self assert:[(webclient serverProtocolDictionary at: (webclient server)) = 'http/1.1' asSymbol  ].
whitespaces

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testconvertToH2Request.st
> +testconvertToH2Request
caps for convert

2018-07-06 12:28 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testconvertToH2WebResponse.st
> +	self assert: (webresponse  protocol ) = (webresponse class standardProtocol ).
whitespaces

2018-07-06 15:42 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/convertToH2Request.with..st
> +	aWebRequest headersDo: [:key :value| request  header add: (key asLowercase) ->  value asString. ].
fixed

2018-07-06 15:42 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/isHttp2..st
> + ^ ((self serverProtocolDictionary at: aServerName) = #h2   or: [ (self serverProtocolDictionary at: aServerName) = #h2c ])
fixed

2018-07-06 15:42 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendPriorKnowlege.contentBlock..st
> +	(self isHttp2: self serverName  )
fixed

2018-07-06 15:43 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +		[
legacy code from WebClient ~ won't fix

2018-07-06 15:43 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendRequest.contentBlock..st
> +sendRequest: aRequest contentBlock: aContentBlock
legacy code from WebClient ~ won't fix

2018-07-06 15:43 UTC, ShirleyNekoDev commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testIsHttp2.st
> +	webclient protocol: #h2c   for: self class exampleServer.
fixed

2018-07-06 15:43 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sendUpgrade.contentBlock..st
> +	aRequest addHeader: 'HTTP2-Settings' value: 'AAMAAABkAARAAAAAAAIAAAAA'.
fixed

2018-07-06 15:43 UTC, Salami555 commented on HTTP2-Core.package/H2WebClient.class/instance/sslConnect.to..st
> +				stream ssl isAlpnSupported ifTrue: [self protocol:  stream ssl alpnSelected asSymbol   for: self serverName]
fixed

2018-07-06 16:30 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/class/standardHttpContent.st
> +	^#[16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r00 16r08 16r00 16r45 16r00
fixed

2018-07-06 16:31 UTC, Salami555 commented on HTTP2-Tests.package/H2Mock.class/instance/lockStreamOf.on..st
> +	^aH2WebClient instVarNamed: 'lastServer' put: aServerName;
fixed

2018-07-06 16:34 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/emptyContentBlock.st
> +	^[:aStream|]
nope, not found

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/exampleContentBlock.st
> +	^[:aStream| aStream nextPutAll: self  exampleContent  ]
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/class/exampleServer.st
> +	^  self exampleScheme , self exampleServerName
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testIsHttp.st
> +	webclient protocol: #h2c   for: self class exampleServer.
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testPrioKnowlegeH2C.st
> +
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testPrioKnowlegeHttp.st
> +	self assert:[(webclient serverProtocolDictionary at: (webclient server)) = 'http/1.1' asSymbol  ].
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testconvertToH2Request.st
> +testconvertToH2Request
fixed

2018-07-06 16:37 UTC, Salami555 commented on HTTP2-Tests.package/H2WebClientTests.class/instance/testconvertToH2WebResponse.st
> +	self assert: (webresponse  protocol ) = (webresponse class standardProtocol ).
fixed

2018-07-06 16:50 UTC, ShirleyNekoDev approved these changes

2018-07-09 13:27 UTC, merged