Refact web client
HPI-SWA-Teaching/SWT17-Project-16 pull request #13
Opened 2018-07-16 19:00 UTC by Charle42

2018-07-16 20:08 UTC, LJBollmeier approved these changes
Funktionalität dorthin, wo's hinghört. Gefällt mir.

2018-07-16 20:08 UTC, BollmeierHPI commented on HTTP2-Core.package/H2WebClient.class/instance/sendPriorKnowlege.contentBlock..st
>  sendPriorKnowlege: aRequest contentBlock: aContentBlock
Die müssen wir unbedingt in sendPriorKnowledge (Betonung auf das "d") umbenennen :D

2018-07-17 05:52 UTC, Hyumiris requested changes
Inhalt gut, jede menge typos

2018-07-17 05:52 UTC, Hyumiris commented on HTTP2-Core.package/H2Request.class/class/contentAsString..st
> +as yet unclassified
no unclassified methods

2018-07-17 05:52 UTC, Hyumiris commented on HTTP2-Core.package/H2Request.class/class/newFrom.with..st
> +as yet unclassified
no unclassified methods

2018-07-17 05:52 UTC, Hyumiris commented on HTTP2-Core.package/H2WebResponse.class/README.md
> +A H2WebResponse is a adpter from H2Response to WebResponse.
typo1: an
typo2: adapter

2018-07-17 05:52 UTC, Hyumiris commented on HTTP2-Core.package/H2WebClient.class/README.md
> +A H2WebClient is a subclass of WebClient witch support HTTP/2.
which

2018-07-17 05:52 UTC, Hyumiris commented on HTTP2-Core.package/H2WebClient.class/README.md
> +	serverProtocolDictionary:		a dictionary to save servernames and his supported protocols.
*their* supported

2018-07-17 08:54 UTC, Hyumiris approved these changes

2018-07-17 08:54 UTC, merged